# Generated by tools/gen_server_api.py from the dedicated server's ListMethods.html - do not edit.
# The typed methods of the dedicated server (TMF, 2011-02-21). Errors of the server raise
# xmlrpc.client.Fault. Structures are TypedDicts: plain dicts at runtime, typed for IDEs and mypy.

import xmlrpc.client
from typing import TypedDict


class ChallengeInfo(TypedDict, total=False):
  # A map. GetChallengeList only fills UId, Name, FileName, Environnement, Author, GoldTime and CopperPrice.
  UId: str
  Name: str
  FileName: str
  Author: str
  Environnement: str
  Mood: str
  BronzeTime: int
  SilverTime: int
  GoldTime: int
  AuthorTime: int
  CopperPrice: int
  LapRace: bool
  NbLaps: int
  NbCheckpoints: int
#


class PlayerInfo(TypedDict, total=False):
  # Flags = ForceSpectator(0,1,2) + IsReferee * 10 + IsPodiumReady * 100 + IsUsingStereoscopy * 1000
  #   + IsManagedByAnOtherServer * 10000 + IsServer * 100000 + HasPlayerSlot * 1000000
  # SpectatorStatus = Spectator + TemporarySpectator * 10 + PureSpectator * 100 + AutoTarget * 1000
  #   + CurrentTargetId * 10000
  Login: str
  NickName: str
  PlayerId: int
  TeamId: int
  SpectatorStatus: int
  LadderRanking: int
  Flags: int
#


class PlayerRanking(TypedDict, total=False):
  Login: str
  NickName: str
  PlayerId: int
  Rank: int
  BestTime: int
  BestCheckpoints: list[int]
  Score: int
  NbrLapsFinished: int
  LadderScore: float
#


class Version(TypedDict, total=False):
  Name: str
  Version: str
  Build: str
#


class Status(TypedDict, total=False):
  Code: int
  Name: str
#


class CallVote(TypedDict, total=False):
  CallerLogin: str
  CmdName: str
  CmdParam: str
#


class ServerApi:
  # Subclasses implement call(method, *params).

  async def call(self, method, *params):
    raise NotImplementedError
  #

  async def authenticate(self, login: str, password: str) -> bool:
    """Allow user authentication by specifying a login and a password, to gain access to the set of
    functionalities corresponding to this authorization level."""
    return await self.call('Authenticate', login, password)
  #

  async def change_auth_password(self, login: str, password: str) -> bool:
    """Change the password for the specified login/user. Only available to SuperAdmin."""
    return await self.call('ChangeAuthPassword', login, password)
  #

  async def enable_callbacks(self, enable: bool) -> bool:
    """Allow the GameServer to call you back."""
    return await self.call('EnableCallbacks', enable)
  #

  async def get_version(self) -> Version:
    """Returns a struct with the Name, Version and Build of the application remotely controled."""
    return await self.call('GetVersion')
  #

  async def call_vote(self, command_xml: str) -> bool:
    """Call a vote for a cmd. The command is a XML string corresponding to an XmlRpc request. Only available to
    Admin."""
    return await self.call('CallVote', command_xml)
  #

  async def call_vote_ex(self, command_xml: str, ratio: float, timeout: int, voter: int) -> bool:
    """Extended call vote. Same as CallVote, but you can additionally supply specific parameters for this vote: a
    ratio, a time out and who is voting. Special timeout values: a timeout of '0' means default, '1' means
    indefinite; a ratio of '-1' means default; Voters values: '0' means only active players, '1' means any
    player, '2' is for everybody, pure spectators included. Only available to Admin."""
    return await self.call('CallVoteEx', command_xml, ratio, timeout, voter)
  #

  async def internal_call_vote(self) -> bool:
    """Used internally by game."""
    return await self.call('InternalCallVote')
  #

  async def cancel_vote(self) -> bool:
    """Cancel the current vote. Only available to Admin."""
    return await self.call('CancelVote')
  #

  async def get_current_call_vote(self) -> CallVote:
    """Returns the vote currently in progress. The returned structure is { CallerLogin, CmdName, CmdParam }."""
    return await self.call('GetCurrentCallVote')
  #

  async def set_call_vote_time_out(self, timeout: int) -> bool:
    """Set a new timeout for waiting for votes. A zero value disables callvote. Only available to Admin. Requires
    a challenge restart to be taken into account."""
    return await self.call('SetCallVoteTimeOut', timeout)
  #

  async def get_call_vote_time_out(self) -> dict:
    """Get the current and next timeout for waiting for votes. The struct returned contains two fields
    'CurrentValue' and 'NextValue'."""
    return await self.call('GetCallVoteTimeOut')
  #

  async def set_call_vote_ratio(self, ratio: float) -> bool:
    """Set a new default ratio for passing a vote. Must lie between 0 and 1. Only available to Admin."""
    return await self.call('SetCallVoteRatio', ratio)
  #

  async def get_call_vote_ratio(self) -> float:
    """Get the current default ratio for passing a vote. This value lies between 0 and 1."""
    return await self.call('GetCallVoteRatio')
  #

  async def set_call_vote_ratios(self, ratios: list) -> bool:
    """Set new ratios for passing specific votes. The parameter is an array of structs {string Command, double
    Ratio}, ratio is in [0,1] or -1 for vote disabled. Only available to Admin."""
    return await self.call('SetCallVoteRatios', ratios)
  #

  async def get_call_vote_ratios(self) -> list:
    """Get the current ratios for passing votes."""
    return await self.call('GetCallVoteRatios')
  #

  async def chat_send_server_message(self, text: str) -> bool:
    """Send a text message to all clients without the server login. Only available to Admin."""
    return await self.call('ChatSendServerMessage', text)
  #

  async def chat_send_server_message_to_language(self, messages: list, login: str) -> bool:
    """Send a localised text message to all clients without the server login, or optionally to a Login (which can
    be a single login or a list of comma-separated logins). The parameter is an array of structures
    {Lang='??', Text='...'}. If no matching language is found, the last text in the array is used. Only
    available to Admin."""
    return await self.call('ChatSendServerMessageToLanguage', messages, login)
  #

  async def chat_send_server_message_to_id(self, text: str, player_id: int) -> bool:
    """Send a text message without the server login to the client with the specified PlayerId. Only available to
    Admin."""
    return await self.call('ChatSendServerMessageToId', text, player_id)
  #

  async def chat_send_server_message_to_login(self, text: str, login: str) -> bool:
    """Send a text message without the server login to the client with the specified login. Login can be a single
    login or a list of comma-separated logins. Only available to Admin."""
    return await self.call('ChatSendServerMessageToLogin', text, login)
  #

  async def chat_send(self, text: str) -> bool:
    """Send a text message to all clients. Only available to Admin."""
    return await self.call('ChatSend', text)
  #

  async def chat_send_to_language(self, messages: list, login: str) -> bool:
    """Send a localised text message to all clients, or optionally to a Login (which can be a single login or a
    list of comma-separated logins). The parameter is an array of structures {Lang='??', Text='...'}. If no
    matching language is found, the last text in the array is used. Only available to Admin."""
    return await self.call('ChatSendToLanguage', messages, login)
  #

  async def chat_send_to_login(self, text: str, login: str) -> bool:
    """Send a text message to the client with the specified login. Login can be a single login or a list of
    comma-separated logins. Only available to Admin."""
    return await self.call('ChatSendToLogin', text, login)
  #

  async def chat_send_to_id(self, text: str, player_id: int) -> bool:
    """Send a text message to the client with the specified PlayerId. Only available to Admin."""
    return await self.call('ChatSendToId', text, player_id)
  #

  async def get_chat_lines(self) -> list:
    """Returns the last chat lines. Maximum of 40 lines. Only available to Admin."""
    return await self.call('GetChatLines')
  #

  async def chat_enable_manual_routing(self, enable: bool, forward_server_messages: bool) -> bool:
    """The chat messages are no longer dispatched to the players, they only go to the rpc callback and the
    controller has to manually forward them. The second (optional) parameter allows all messages from the
    server to be automatically forwarded. Only available to Admin."""
    return await self.call('ChatEnableManualRouting', enable, forward_server_messages)
  #

  async def chat_forward_to_login(self, text: str, sender_login: str, dest_login: str) -> bool:
    """(Text, SenderLogin, DestLogin) Send a text message to the specified DestLogin (or everybody if empty) on
    behalf of SenderLogin. DestLogin can be a single login or a list of comma-separated logins. Only available
    if manual routing is enabled. Only available to Admin."""
    return await self.call('ChatForwardToLogin', text, sender_login, dest_login)
  #

  async def send_notice(self, text: str, avatar_login: str, duration: int) -> bool:
    """Display a notice on all clients. The parameters are the text message to display, and the login of the
    avatar to display next to it (or '' for no avatar), and an optional 'max duration' in seconds (default:
    3). Only available to Admin."""
    return await self.call('SendNotice', text, avatar_login, duration)
  #

  async def send_notice_to_id(self, player_id: int, text: str, avatar_id: int, duration: int) -> bool:
    """Display a notice on the client with the specified UId. The parameters are the Uid of the client to whom
    the notice is sent, the text message to display, and the UId of the avatar to display next to it (or '255'
    for no avatar), and an optional 'max duration' in seconds (default: 3). Only available to Admin."""
    return await self.call('SendNoticeToId', player_id, text, avatar_id, duration)
  #

  async def send_notice_to_login(self, login: str, text: str, avatar_login: str, duration: int) -> bool:
    """Display a notice on the client with the specified login. The parameters are the login of the client to
    whom the notice is sent, the text message to display, and the login of the avatar to display next to it
    (or '' for no avatar), and an optional 'max duration' in seconds (default: 3). Login can be a single login
    or a list of comma-separated logins. Only available to Admin."""
    return await self.call('SendNoticeToLogin', login, text, avatar_login, duration)
  #

  async def send_display_manialink_page(self, xml: str, timeout: int, hide_on_click: bool) -> bool:
    """Display a manialink page on all clients. The parameters are the xml description of the page to display, a
    timeout to autohide it (0 = permanent), and a boolean to indicate whether the page must be hidden as soon
    as the user clicks on a page option. Only available to Admin."""
    return await self.call('SendDisplayManialinkPage', xml, timeout, hide_on_click)
  #

  async def send_display_manialink_page_to_id(self, player_id: int, xml: str, timeout: int, hide_on_click: bool) -> bool:
    """Display a manialink page on the client with the specified UId. The first parameter is the UId of the
    player, the other are identical to 'SendDisplayManialinkPage'. Only available to Admin."""
    return await self.call('SendDisplayManialinkPageToId', player_id, xml, timeout, hide_on_click)
  #

  async def send_display_manialink_page_to_login(self, login: str, xml: str, timeout: int, hide_on_click: bool) -> bool:
    """Display a manialink page on the client with the specified login. The first parameter is the login of the
    player, the other are identical to 'SendDisplayManialinkPage'. Login can be a single login or a list of
    comma-separated logins. Only available to Admin."""
    return await self.call('SendDisplayManialinkPageToLogin', login, xml, timeout, hide_on_click)
  #

  async def send_hide_manialink_page(self) -> bool:
    """Hide the displayed manialink page on all clients. Only available to Admin."""
    return await self.call('SendHideManialinkPage')
  #

  async def send_hide_manialink_page_to_id(self, player_id: int) -> bool:
    """Hide the displayed manialink page on the client with the specified UId. Only available to Admin."""
    return await self.call('SendHideManialinkPageToId', player_id)
  #

  async def send_hide_manialink_page_to_login(self, login: str) -> bool:
    """Hide the displayed manialink page on the client with the specified login. Login can be a single login or a
    list of comma-separated logins. Only available to Admin."""
    return await self.call('SendHideManialinkPageToLogin', login)
  #

  async def get_manialink_page_answers(self) -> list:
    """Returns the latest results from the current manialink page, as an array of structs {string Login, int
    PlayerId, int Result} Result==0 -> no answer, Result>0.... -> answer from the player."""
    return await self.call('GetManialinkPageAnswers')
  #

  async def kick(self, login: str, message: str = '') -> bool:
    """Kick the player with the specified login, with an optional message. Only available to Admin."""
    return await self.call('Kick', login, message)
  #

  async def kick_id(self, player_id: int, message: str = '') -> bool:
    """Kick the player with the specified PlayerId, with an optional message. Only available to Admin."""
    return await self.call('KickId', player_id, message)
  #

  async def ban(self, login: str, message: str = '') -> bool:
    """Ban the player with the specified login, with an optional message. Only available to Admin."""
    return await self.call('Ban', login, message)
  #

  async def ban_and_black_list(self, login: str, message: str, save: bool) -> bool:
    """Ban the player with the specified login, with a message. Add it to the black list, and optionally save the
    new list. Only available to Admin."""
    return await self.call('BanAndBlackList', login, message, save)
  #

  async def ban_id(self, player_id: int, message: str = '') -> bool:
    """Ban the player with the specified PlayerId, with an optional message. Only available to Admin."""
    return await self.call('BanId', player_id, message)
  #

  async def un_ban(self, login: str) -> bool:
    """Unban the player with the specified client name. Only available to Admin."""
    return await self.call('UnBan', login)
  #

  async def clean_ban_list(self) -> bool:
    """Clean the ban list of the server. Only available to Admin."""
    return await self.call('CleanBanList')
  #

  async def get_ban_list(self, count: int, start: int) -> list:
    """Returns the list of banned players. This method takes two parameters. The first parameter specifies the
    maximum number of infos to be returned, and the second one the starting index in the list. The list is an
    array of structures. Each structure contains the following fields : Login, ClientName and IPAddress."""
    return await self.call('GetBanList', count, start)
  #

  async def black_list(self, login: str) -> bool:
    """Blacklist the player with the specified login. Only available to SuperAdmin."""
    return await self.call('BlackList', login)
  #

  async def black_list_id(self, player_id: int) -> bool:
    """Blacklist the player with the specified PlayerId. Only available to SuperAdmin."""
    return await self.call('BlackListId', player_id)
  #

  async def un_black_list(self, login: str) -> bool:
    """UnBlackList the player with the specified login. Only available to SuperAdmin."""
    return await self.call('UnBlackList', login)
  #

  async def clean_black_list(self) -> bool:
    """Clean the blacklist of the server. Only available to SuperAdmin."""
    return await self.call('CleanBlackList')
  #

  async def get_black_list(self, count: int, start: int) -> list:
    """Returns the list of blacklisted players. This method takes two parameters. The first parameter specifies
    the maximum number of infos to be returned, and the second one the starting index in the list. The list is
    an array of structures. Each structure contains the following fields : Login."""
    return await self.call('GetBlackList', count, start)
  #

  async def load_black_list(self, filename: str) -> bool:
    """Load the black list file with the specified file name. Only available to Admin."""
    return await self.call('LoadBlackList', filename)
  #

  async def save_black_list(self, filename: str) -> bool:
    """Save the black list in the file with specified file name. Only available to Admin."""
    return await self.call('SaveBlackList', filename)
  #

  async def add_guest(self, login: str) -> bool:
    """Add the player with the specified login on the guest list. Only available to Admin."""
    return await self.call('AddGuest', login)
  #

  async def add_guest_id(self, player_id: int) -> bool:
    """Add the player with the specified PlayerId on the guest list. Only available to Admin."""
    return await self.call('AddGuestId', player_id)
  #

  async def remove_guest(self, login: str) -> bool:
    """Remove the player with the specified login from the guest list. Only available to Admin."""
    return await self.call('RemoveGuest', login)
  #

  async def remove_guest_id(self, player_id: int) -> bool:
    """Remove the player with the specified PlayerId from the guest list. Only available to Admin."""
    return await self.call('RemoveGuestId', player_id)
  #

  async def clean_guest_list(self) -> bool:
    """Clean the guest list of the server. Only available to Admin."""
    return await self.call('CleanGuestList')
  #

  async def get_guest_list(self, count: int, start: int) -> list:
    """Returns the list of players on the guest list. This method takes two parameters. The first parameter
    specifies the maximum number of infos to be returned, and the second one the starting index in the list.
    The list is an array of structures. Each structure contains the following fields : Login."""
    return await self.call('GetGuestList', count, start)
  #

  async def load_guest_list(self, filename: str) -> bool:
    """Load the guest list file with the specified file name. Only available to Admin."""
    return await self.call('LoadGuestList', filename)
  #

  async def save_guest_list(self, filename: str) -> bool:
    """Save the guest list in the file with specified file name. Only available to Admin."""
    return await self.call('SaveGuestList', filename)
  #

  async def set_buddy_notification(self, login: str, enabled: bool) -> bool:
    """Sets whether buddy notifications should be sent in the chat. login is the login of the player, or '' for
    global setting, and enabled is the value. Only available to Admin."""
    return await self.call('SetBuddyNotification', login, enabled)
  #

  async def get_buddy_notification(self, login: str) -> bool:
    """Gets whether buddy notifications are enabled for login, or '' to get the global setting."""
    return await self.call('GetBuddyNotification', login)
  #

  async def write_file(self, filename: str, data: xmlrpc.client.Binary) -> bool:
    """Write the data to the specified file. The filename is relative to the Tracks path. Only available to
    Admin."""
    return await self.call('WriteFile', filename, data)
  #

  async def tunnel_send_data_to_id(self, player_id: int, data: xmlrpc.client.Binary) -> bool:
    """Send the data to the specified player. Only available to Admin."""
    return await self.call('TunnelSendDataToId', player_id, data)
  #

  async def tunnel_send_data_to_login(self, login: str, data: xmlrpc.client.Binary) -> bool:
    """Send the data to the specified player. Login can be a single login or a list of comma-separated logins.
    Only available to Admin."""
    return await self.call('TunnelSendDataToLogin', login, data)
  #

  async def echo(self, first: str, second: str) -> bool:
    """Just log the parameters and invoke a callback. Can be used to talk to other xmlrpc clients connected, or
    to make custom votes. If used in a callvote, the first parameter will be used as the vote message on the
    clients. Only available to Admin."""
    return await self.call('Echo', first, second)
  #

  async def ignore(self, login: str) -> bool:
    """Ignore the player with the specified login. Only available to Admin."""
    return await self.call('Ignore', login)
  #

  async def ignore_id(self, player_id: int) -> bool:
    """Ignore the player with the specified PlayerId. Only available to Admin."""
    return await self.call('IgnoreId', player_id)
  #

  async def un_ignore(self, login: str) -> bool:
    """Unignore the player with the specified login. Only available to Admin."""
    return await self.call('UnIgnore', login)
  #

  async def un_ignore_id(self, player_id: int) -> bool:
    """Unignore the player with the specified PlayerId. Only available to Admin."""
    return await self.call('UnIgnoreId', player_id)
  #

  async def clean_ignore_list(self) -> bool:
    """Clean the ignore list of the server. Only available to Admin."""
    return await self.call('CleanIgnoreList')
  #

  async def get_ignore_list(self, count: int, start: int) -> list:
    """Returns the list of ignored players. This method takes two parameters. The first parameter specifies the
    maximum number of infos to be returned, and the second one the starting index in the list. The list is an
    array of structures. Each structure contains the following fields : Login."""
    return await self.call('GetIgnoreList', count, start)
  #

  async def pay(self, login: str, coppers: int, label: str) -> int:
    """Pay coppers from the server account to a player, returns the BillId. This method takes three parameters:
    Login of the payee, Coppers to pay and a Label to send with the payment. The creation of the transaction
    itself may cost coppers, so you need to have coppers on the server account. Only available to Admin."""
    return await self.call('Pay', login, coppers, label)
  #

  async def send_bill(self, login_from: str, coppers: int, label: str, login_to: str) -> int:
    """Create a bill, send it to a player, and return the BillId. This method takes four parameters: LoginFrom of
    the payer, Coppers the player has to pay, Label of the transaction and an optional LoginTo of the payee
    (if empty string, then the server account is used). The creation of the transaction itself may cost
    coppers, so you need to have coppers on the server account. Only available to Admin."""
    return await self.call('SendBill', login_from, coppers, label, login_to)
  #

  async def get_bill_state(self, bill_id: int) -> dict:
    """Returns the current state of a bill. This method takes one parameter, the BillId. Returns a struct
    containing State, StateName and TransactionId. Possible enum values are: CreatingTransaction, Issued,
    ValidatingPayement, Payed, Refused, Error."""
    return await self.call('GetBillState', bill_id)
  #

  async def get_server_coppers(self) -> int:
    """Returns the current number of coppers on the server account."""
    return await self.call('GetServerCoppers')
  #

  async def get_system_info(self) -> dict:
    """Get some system infos, including connection rates (in kbps)."""
    return await self.call('GetSystemInfo')
  #

  async def set_connection_rates(self, download: int, upload: int) -> bool:
    """Set the download and upload rates (in kbps)."""
    return await self.call('SetConnectionRates', download, upload)
  #

  async def set_server_name(self, name: str) -> bool:
    """Set a new server name in utf8 format. Only available to Admin."""
    return await self.call('SetServerName', name)
  #

  async def get_server_name(self) -> str:
    """Get the server name in utf8 format."""
    return await self.call('GetServerName')
  #

  async def set_server_comment(self, comment: str) -> bool:
    """Set a new server comment in utf8 format. Only available to Admin."""
    return await self.call('SetServerComment', comment)
  #

  async def get_server_comment(self) -> str:
    """Get the server comment in utf8 format."""
    return await self.call('GetServerComment')
  #

  async def set_hide_server(self, hidden: int) -> bool:
    """Set whether the server should be hidden from the public server list (0 = visible, 1 = always hidden, 2 =
    hidden from nations). Only available to Admin."""
    return await self.call('SetHideServer', hidden)
  #

  async def get_hide_server(self) -> int:
    """Get whether the server wants to be hidden from the public server list."""
    return await self.call('GetHideServer')
  #

  async def is_relay_server(self) -> bool:
    """Returns true if this is a relay server."""
    return await self.call('IsRelayServer')
  #

  async def set_server_password(self, password: str) -> bool:
    """Set a new password for the server. Only available to Admin."""
    return await self.call('SetServerPassword', password)
  #

  async def get_server_password(self) -> str:
    """Get the server password if called as Admin or Super Admin, else returns if a password is needed or not."""
    return await self.call('GetServerPassword')
  #

  async def set_server_password_for_spectator(self, password: str) -> bool:
    """Set a new password for the spectator mode. Only available to Admin."""
    return await self.call('SetServerPasswordForSpectator', password)
  #

  async def get_server_password_for_spectator(self) -> str:
    """Get the password for spectator mode if called as Admin or Super Admin, else returns if a password is
    needed or not."""
    return await self.call('GetServerPasswordForSpectator')
  #

  async def set_max_players(self, count: int) -> bool:
    """Set a new maximum number of players. Only available to Admin. Requires a challenge restart to be taken
    into account."""
    return await self.call('SetMaxPlayers', count)
  #

  async def get_max_players(self) -> dict:
    """Get the current and next maximum number of players allowed on server. The struct returned contains two
    fields CurrentValue and NextValue."""
    return await self.call('GetMaxPlayers')
  #

  async def set_max_spectators(self, count: int) -> bool:
    """Set a new maximum number of Spectators. Only available to Admin. Requires a challenge restart to be taken
    into account."""
    return await self.call('SetMaxSpectators', count)
  #

  async def get_max_spectators(self) -> dict:
    """Get the current and next maximum number of Spectators allowed on server. The struct returned contains two
    fields CurrentValue and NextValue."""
    return await self.call('GetMaxSpectators')
  #

  async def enable_p2p_upload(self, enable: bool) -> bool:
    """Enable or disable peer-to-peer upload from server. Only available to Admin."""
    return await self.call('EnableP2PUpload', enable)
  #

  async def is_p2p_upload(self) -> bool:
    """Returns if the peer-to-peer upload from server is enabled."""
    return await self.call('IsP2PUpload')
  #

  async def enable_p2p_download(self, enable: bool) -> bool:
    """Enable or disable peer-to-peer download for server. Only available to Admin."""
    return await self.call('EnableP2PDownload', enable)
  #

  async def is_p2p_download(self) -> bool:
    """Returns if the peer-to-peer download for server is enabled."""
    return await self.call('IsP2PDownload')
  #

  async def allow_challenge_download(self, allow: bool) -> bool:
    """Allow clients to download challenges from the server. Only available to Admin."""
    return await self.call('AllowChallengeDownload', allow)
  #

  async def is_challenge_download_allowed(self) -> bool:
    """Returns if clients can download challenges from the server."""
    return await self.call('IsChallengeDownloadAllowed')
  #

  async def auto_save_replays(self, enable: bool) -> bool:
    """Enable the autosaving of all replays (vizualisable replays with all players, but not validable) on the
    server. Only available to SuperAdmin."""
    return await self.call('AutoSaveReplays', enable)
  #

  async def auto_save_validation_replays(self, enable: bool) -> bool:
    """Enable the autosaving on the server of validation replays, every time a player makes a new time. Only
    available to SuperAdmin."""
    return await self.call('AutoSaveValidationReplays', enable)
  #

  async def is_auto_save_replays_enabled(self) -> bool:
    """Returns if autosaving of all replays is enabled on the server."""
    return await self.call('IsAutoSaveReplaysEnabled')
  #

  async def is_auto_save_validation_replays_enabled(self) -> bool:
    """Returns if autosaving of validation replays is enabled on the server."""
    return await self.call('IsAutoSaveValidationReplaysEnabled')
  #

  async def save_current_replay(self, filename: str = '') -> bool:
    """Saves the current replay (vizualisable replays with all players, but not validable). Pass a filename, or
    '' for an automatic filename. Only available to Admin."""
    return await self.call('SaveCurrentReplay', filename)
  #

  async def save_best_ghosts_replay(self, login: str, filename: str = '') -> bool:
    """Saves a replay with the ghost of all the players' best race. First parameter is the login of the player
    (or '' for all players), Second parameter is the filename, or '' for an automatic filename. Only available
    to Admin."""
    return await self.call('SaveBestGhostsReplay', login, filename)
  #

  async def get_validation_replay(self, login: str) -> xmlrpc.client.Binary:
    """Returns a replay containing the data needed to validate the current best time of the player. The parameter
    is the login of the player."""
    return await self.call('GetValidationReplay', login)
  #

  async def set_ladder_mode(self, mode: int) -> bool:
    """Set a new ladder mode between ladder disabled (0) and forced (1). Only available to Admin. Requires a
    challenge restart to be taken into account."""
    return await self.call('SetLadderMode', mode)
  #

  async def get_ladder_mode(self) -> dict:
    """Get the current and next ladder mode on server. The struct returned contains two fields CurrentValue and
    NextValue."""
    return await self.call('GetLadderMode')
  #

  async def get_ladder_server_limits(self) -> dict:
    """Get the ladder points limit for the players allowed on this server. The struct returned contains two
    fields LadderServerLimitMin and LadderServerLimitMax."""
    return await self.call('GetLadderServerLimits')
  #

  async def set_vehicle_net_quality(self, quality: int) -> bool:
    """Set the network vehicle quality to Fast (0) or High (1). Only available to Admin. Requires a challenge
    restart to be taken into account."""
    return await self.call('SetVehicleNetQuality', quality)
  #

  async def get_vehicle_net_quality(self) -> dict:
    """Get the current and next network vehicle quality on server. The struct returned contains two fields
    CurrentValue and NextValue."""
    return await self.call('GetVehicleNetQuality')
  #

  async def set_server_options(self, options: dict) -> bool:
    """Set new server options using the struct passed as parameters. This struct must contain the following
    fields : Name, Comment, Password, PasswordForSpectator, NextMaxPlayers, NextMaxSpectators, IsP2PUpload,
    IsP2PDownload, NextLadderMode, NextVehicleNetQuality, NextCallVoteTimeOut, CallVoteRatio,
    AllowChallengeDownload, AutoSaveReplays, and optionally for forever: RefereePassword, RefereeMode,
    AutoSaveValidationReplays, HideServer, UseChangingValidationSeed. Only available to Admin. A change of
    NextMaxPlayers, NextMaxSpectators, NextLadderMode, NextVehicleNetQuality, NextCallVoteTimeOut or
    UseChangingValidationSeed requires a challenge restart to be taken into account."""
    return await self.call('SetServerOptions', options)
  #

  async def get_server_options(self, version: int = 1) -> dict:
    """Optional parameter for compatibility: struct version (0 = united, 1 = forever). Returns a struct
    containing the server options: Name, Comment, Password, PasswordForSpectator, CurrentMaxPlayers,
    NextMaxPlayers, CurrentMaxSpectators, NextMaxSpectators, IsP2PUpload, IsP2PDownload, CurrentLadderMode,
    NextLadderMode, CurrentVehicleNetQuality, NextVehicleNetQuality, CurrentCallVoteTimeOut,
    NextCallVoteTimeOut, CallVoteRatio, AllowChallengeDownload and AutoSaveReplays, and additionally for
    forever: RefereePassword, RefereeMode, AutoSaveValidationReplays, HideServer,
    CurrentUseChangingValidationSeed, NextUseChangingValidationSeed."""
    return await self.call('GetServerOptions', version)
  #

  async def set_server_pack_mask(self, pack_mask: str) -> bool:
    """Defines the packmask of the server. Can be 'United', 'Nations', 'Sunrise', 'Original', or any of the
    environment names. (Only challenges matching the packmask will be allowed on the server, so that player
    connecting to it know what to expect.) Only available when the server is stopped. Only available to Admin."""
    return await self.call('SetServerPackMask', pack_mask)
  #

  async def get_server_pack_mask(self) -> str:
    """Get the packmask of the server."""
    return await self.call('GetServerPackMask')
  #

  async def set_forced_mods(self, override: bool, mods: list) -> bool:
    """Set the mods to apply on the clients. Parameters: Override, if true even the challenges with a mod will be
    overridden by the server setting; and Mods, an array of structures [{EnvName, Url}, ...]. Requires a
    challenge restart to be taken into account. Only available to Admin."""
    return await self.call('SetForcedMods', override, mods)
  #

  async def get_forced_mods(self) -> dict:
    """Get the mods settings."""
    return await self.call('GetForcedMods')
  #

  async def set_forced_music(self, override: bool, url_or_filename: str) -> bool:
    """Set the music to play on the clients. Parameters: Override, if true even the challenges with a custom
    music will be overridden by the server setting, and a UrlOrFileName for the music. Requires a challenge
    restart to be taken into account. Only available to Admin."""
    return await self.call('SetForcedMusic', override, url_or_filename)
  #

  async def get_forced_music(self) -> dict:
    """Get the music setting."""
    return await self.call('GetForcedMusic')
  #

  async def set_forced_skins(self, skins: list) -> bool:
    """Defines a list of remappings for player skins. It expects a list of structs Orig, Name, Checksum, Url.
    Orig is the name of the skin to remap, or '*' for any other. Name, Checksum, Url define the skin to use.
    (They are optional, you may set value '' for any of those. All 3 null means same as Orig). Will only
    affect players connecting after the value is set. Only available to Admin."""
    return await self.call('SetForcedSkins', skins)
  #

  async def get_forced_skins(self) -> list:
    """Get the current forced skins."""
    return await self.call('GetForcedSkins')
  #

  async def get_last_connection_error_message(self) -> str:
    """Returns the last error message for an internet connection. Only available to Admin."""
    return await self.call('GetLastConnectionErrorMessage')
  #

  async def set_referee_password(self, password: str) -> bool:
    """Set a new password for the referee mode. Only available to Admin."""
    return await self.call('SetRefereePassword', password)
  #

  async def get_referee_password(self) -> str:
    """Get the password for referee mode if called as Admin or Super Admin, else returns if a password is needed
    or not."""
    return await self.call('GetRefereePassword')
  #

  async def set_referee_mode(self, mode: int) -> bool:
    """Set the referee validation mode. 0 = validate the top3 players, 1 = validate all players. Only available
    to Admin."""
    return await self.call('SetRefereeMode', mode)
  #

  async def get_referee_mode(self) -> int:
    """Get the referee validation mode."""
    return await self.call('GetRefereeMode')
  #

  async def set_use_changing_validation_seed(self, enable: bool) -> bool:
    """Set whether the game should use a variable validation seed or not. Only available to Admin. Requires a
    challenge restart to be taken into account."""
    return await self.call('SetUseChangingValidationSeed', enable)
  #

  async def get_use_changing_validation_seed(self) -> dict:
    """Get the current and next value of UseChangingValidationSeed. The struct returned contains two fields
    CurrentValue and NextValue."""
    return await self.call('GetUseChangingValidationSeed')
  #

  async def set_warm_up(self, enable: bool) -> bool:
    """Sets whether the server is in warm-up phase or not. Only available to Admin."""
    return await self.call('SetWarmUp', enable)
  #

  async def get_warm_up(self) -> bool:
    """Returns whether the server is in warm-up phase."""
    return await self.call('GetWarmUp')
  #

  async def challenge_restart(self) -> bool:
    """Restarts the challenge, with an optional boolean parameter DontClearCupScores (only available in cup
    mode). Only available to Admin."""
    return await self.call('ChallengeRestart')
  #

  async def restart_challenge(self) -> bool:
    """Restarts the challenge, with an optional boolean parameter DontClearCupScores (only available in cup
    mode). Only available to Admin."""
    return await self.call('RestartChallenge')
  #

  async def next_challenge(self) -> bool:
    """Switch to next challenge, with an optional boolean parameter DontClearCupScores (only available in cup
    mode). Only available to Admin."""
    return await self.call('NextChallenge')
  #

  async def stop_server(self) -> bool:
    """Stop the server. Only available to SuperAdmin."""
    return await self.call('StopServer')
  #

  async def force_end_round(self) -> bool:
    """In Rounds or Laps mode, force the end of round without waiting for all players to giveup/finish. Only
    available to Admin."""
    return await self.call('ForceEndRound')
  #

  async def set_game_infos(self, game_infos: dict) -> bool:
    """Set new game settings using the struct passed as parameters. This struct must contain the following fields
    : GameMode, ChatTime, RoundsPointsLimit, RoundsUseNewRules, RoundsForcedLaps, TimeAttackLimit,
    TimeAttackSynchStartPeriod, TeamPointsLimit, TeamMaxPoints, TeamUseNewRules, LapsNbLaps, LapsTimeLimit,
    FinishTimeout, and optionally: AllWarmUpDuration, DisableRespawn, ForceShowAllOpponents,
    RoundsPointsLimitNewRules, TeamPointsLimitNewRules, CupPointsLimit, CupRoundsPerChallenge, CupNbWinners,
    CupWarmUpDuration. Only available to Admin. Requires a challenge restart to be taken into account."""
    return await self.call('SetGameInfos', game_infos)
  #

  async def get_current_game_info(self, version: int = 1) -> dict:
    """Optional parameter for compatibility: struct version (0 = united, 1 = forever). Returns a struct
    containing the current game settings, ie: GameMode, ChatTime, NbChallenge, RoundsPointsLimit,
    RoundsUseNewRules, RoundsForcedLaps, TimeAttackLimit, TimeAttackSynchStartPeriod, TeamPointsLimit,
    TeamMaxPoints, TeamUseNewRules, LapsNbLaps, LapsTimeLimit, FinishTimeout, and additionally for version 1:
    AllWarmUpDuration, DisableRespawn, ForceShowAllOpponents, RoundsPointsLimitNewRules,
    TeamPointsLimitNewRules, CupPointsLimit, CupRoundsPerChallenge, CupNbWinners, CupWarmUpDuration."""
    return await self.call('GetCurrentGameInfo', version)
  #

  async def get_next_game_info(self, version: int = 1) -> dict:
    """Optional parameter for compatibility: struct version (0 = united, 1 = forever). Returns a struct
    containing the game settings for the next challenge, ie: GameMode, ChatTime, NbChallenge,
    RoundsPointsLimit, RoundsUseNewRules, RoundsForcedLaps, TimeAttackLimit, TimeAttackSynchStartPeriod,
    TeamPointsLimit, TeamMaxPoints, TeamUseNewRules, LapsNbLaps, LapsTimeLimit, FinishTimeout, and
    additionally for version 1: AllWarmUpDuration, DisableRespawn, ForceShowAllOpponents,
    RoundsPointsLimitNewRules, TeamPointsLimitNewRules, CupPointsLimit, CupRoundsPerChallenge, CupNbWinners,
    CupWarmUpDuration."""
    return await self.call('GetNextGameInfo', version)
  #

  async def get_game_infos(self, version: int = 1) -> dict:
    """Optional parameter for compatibility: struct version (0 = united, 1 = forever). Returns a struct
    containing two other structures, the first containing the current game settings and the second the game
    settings for next challenge. The first structure is named CurrentGameInfos and the second NextGameInfos."""
    return await self.call('GetGameInfos', version)
  #

  async def set_game_mode(self, mode: int) -> bool:
    """Set a new game mode between Rounds (0), TimeAttack (1), Team (2), Laps (3), Stunts (4) and Cup (5). Only
    available to Admin. Requires a challenge restart to be taken into account."""
    return await self.call('SetGameMode', mode)
  #

  async def get_game_mode(self) -> int:
    """Get the current game mode."""
    return await self.call('GetGameMode')
  #

  async def set_chat_time(self, ms: int) -> bool:
    """Set a new chat time value in milliseconds (actually 'chat time' is the duration of the end race podium, 0
    means no podium displayed.). Only available to Admin."""
    return await self.call('SetChatTime', ms)
  #

  async def get_chat_time(self) -> dict:
    """Get the current and next chat time. The struct returned contains two fields CurrentValue and NextValue."""
    return await self.call('GetChatTime')
  #

  async def set_finish_timeout(self, ms: int) -> bool:
    """Set a new finish timeout (for rounds/laps mode) value in milliseconds. 0 means default. 1 means adaptative
    to the duration of the challenge. Only available to Admin. Requires a challenge restart to be taken into
    account."""
    return await self.call('SetFinishTimeout', ms)
  #

  async def get_finish_timeout(self) -> dict:
    """Get the current and next FinishTimeout. The struct returned contains two fields CurrentValue and
    NextValue."""
    return await self.call('GetFinishTimeout')
  #

  async def set_all_warm_up_duration(self, rounds: int) -> bool:
    """Set whether to enable the automatic warm-up phase in all modes. 0 = no, otherwise it's the duration of the
    phase, expressed in number of rounds (in rounds/team mode), or in number of times the gold medal time
    (other modes). Only available to Admin. Requires a challenge restart to be taken into account."""
    return await self.call('SetAllWarmUpDuration', rounds)
  #

  async def get_all_warm_up_duration(self) -> dict:
    """Get whether the automatic warm-up phase is enabled in all modes. The struct returned contains two fields
    CurrentValue and NextValue."""
    return await self.call('GetAllWarmUpDuration')
  #

  async def set_disable_respawn(self, disable: bool) -> bool:
    """Set whether to disallow players to respawn. Only available to Admin. Requires a challenge restart to be
    taken into account."""
    return await self.call('SetDisableRespawn', disable)
  #

  async def get_disable_respawn(self) -> dict:
    """Get whether players are disallowed to respawn. The struct returned contains two fields CurrentValue and
    NextValue."""
    return await self.call('GetDisableRespawn')
  #

  async def set_force_show_all_opponents(self, count: int) -> bool:
    """Set whether to override the players preferences and always display all opponents (0=no override, 1=show
    all, other value=minimum number of opponents). Only available to Admin. Requires a challenge restart to be
    taken into account."""
    return await self.call('SetForceShowAllOpponents', count)
  #

  async def get_force_show_all_opponents(self) -> dict:
    """Get whether players are forced to show all opponents. The struct returned contains two fields CurrentValue
    and NextValue."""
    return await self.call('GetForceShowAllOpponents')
  #

  async def set_time_attack_limit(self, ms: int) -> bool:
    """Set a new time limit for time attack mode. Only available to Admin. Requires a challenge restart to be
    taken into account."""
    return await self.call('SetTimeAttackLimit', ms)
  #

  async def get_time_attack_limit(self) -> dict:
    """Get the current and next time limit for time attack mode. The struct returned contains two fields
    CurrentValue and NextValue."""
    return await self.call('GetTimeAttackLimit')
  #

  async def set_time_attack_synch_start_period(self, ms: int) -> bool:
    """Set a new synchronized start period for time attack mode. Only available to Admin. Requires a challenge
    restart to be taken into account."""
    return await self.call('SetTimeAttackSynchStartPeriod', ms)
  #

  async def get_time_attack_synch_start_period(self) -> dict:
    """Get the current and synchronized start period for time attack mode. The struct returned contains two
    fields CurrentValue and NextValue."""
    return await self.call('GetTimeAttackSynchStartPeriod')
  #

  async def set_laps_time_limit(self, ms: int) -> bool:
    """Set a new time limit for laps mode. Only available to Admin. Requires a challenge restart to be taken into
    account."""
    return await self.call('SetLapsTimeLimit', ms)
  #

  async def get_laps_time_limit(self) -> dict:
    """Get the current and next time limit for laps mode. The struct returned contains two fields CurrentValue
    and NextValue."""
    return await self.call('GetLapsTimeLimit')
  #

  async def set_nb_laps(self, laps: int) -> bool:
    """Set a new number of laps for laps mode. Only available to Admin. Requires a challenge restart to be taken
    into account."""
    return await self.call('SetNbLaps', laps)
  #

  async def get_nb_laps(self) -> dict:
    """Get the current and next number of laps for laps mode. The struct returned contains two fields
    CurrentValue and NextValue."""
    return await self.call('GetNbLaps')
  #

  async def set_round_forced_laps(self, laps: int) -> bool:
    """Set a new number of laps for rounds mode (0 = default, use the number of laps from the challenges,
    otherwise forces the number of rounds for multilaps challenges). Only available to Admin. Requires a
    challenge restart to be taken into account."""
    return await self.call('SetRoundForcedLaps', laps)
  #

  async def get_round_forced_laps(self) -> dict:
    """Get the current and next number of laps for rounds mode. The struct returned contains two fields
    CurrentValue and NextValue."""
    return await self.call('GetRoundForcedLaps')
  #

  async def set_round_points_limit(self, points: int) -> bool:
    """Set a new points limit for rounds mode (value set depends on UseNewRulesRound). Only available to Admin.
    Requires a challenge restart to be taken into account."""
    return await self.call('SetRoundPointsLimit', points)
  #

  async def get_round_points_limit(self) -> dict:
    """Get the current and next points limit for rounds mode (values returned depend on UseNewRulesRound). The
    struct returned contains two fields CurrentValue and NextValue."""
    return await self.call('GetRoundPointsLimit')
  #

  async def set_round_custom_points(self, points: list, relax: bool) -> bool:
    """Set the points used for the scores in rounds mode. Points is an array of decreasing integers for the
    players from the first to last. And you can add an optional boolean to relax the constraint checking on
    the scores. Only available to Admin."""
    return await self.call('SetRoundCustomPoints', points, relax)
  #

  async def get_round_custom_points(self) -> list:
    """Gets the points used for the scores in rounds mode."""
    return await self.call('GetRoundCustomPoints')
  #

  async def set_use_new_rules_round(self, enable: bool) -> bool:
    """Set if new rules are used for rounds mode. Only available to Admin. Requires a challenge restart to be
    taken into account."""
    return await self.call('SetUseNewRulesRound', enable)
  #

  async def get_use_new_rules_round(self) -> dict:
    """Get if the new rules are used for rounds mode (Current and next values). The struct returned contains two
    fields CurrentValue and NextValue."""
    return await self.call('GetUseNewRulesRound')
  #

  async def set_team_points_limit(self, points: int) -> bool:
    """Set a new points limit for team mode (value set depends on UseNewRulesTeam). Only available to Admin.
    Requires a challenge restart to be taken into account."""
    return await self.call('SetTeamPointsLimit', points)
  #

  async def get_team_points_limit(self) -> dict:
    """Get the current and next points limit for team mode (values returned depend on UseNewRulesTeam). The
    struct returned contains two fields CurrentValue and NextValue."""
    return await self.call('GetTeamPointsLimit')
  #

  async def set_max_points_team(self, points: int) -> bool:
    """Set a new number of maximum points per round for team mode. Only available to Admin. Requires a challenge
    restart to be taken into account."""
    return await self.call('SetMaxPointsTeam', points)
  #

  async def get_max_points_team(self) -> dict:
    """Get the current and next number of maximum points per round for team mode. The struct returned contains
    two fields CurrentValue and NextValue."""
    return await self.call('GetMaxPointsTeam')
  #

  async def set_use_new_rules_team(self, enable: bool) -> bool:
    """Set if new rules are used for team mode. Only available to Admin. Requires a challenge restart to be taken
    into account."""
    return await self.call('SetUseNewRulesTeam', enable)
  #

  async def get_use_new_rules_team(self) -> dict:
    """Get if the new rules are used for team mode (Current and next values). The struct returned contains two
    fields CurrentValue and NextValue."""
    return await self.call('GetUseNewRulesTeam')
  #

  async def set_cup_points_limit(self, points: int) -> bool:
    """Set the points needed for victory in Cup mode. Only available to Admin. Requires a challenge restart to be
    taken into account."""
    return await self.call('SetCupPointsLimit', points)
  #

  async def get_cup_points_limit(self) -> dict:
    """Get the points needed for victory in Cup mode. The struct returned contains two fields CurrentValue and
    NextValue."""
    return await self.call('GetCupPointsLimit')
  #

  async def set_cup_rounds_per_challenge(self, rounds: int) -> bool:
    """Sets the number of rounds before going to next challenge in Cup mode. Only available to Admin. Requires a
    challenge restart to be taken into account."""
    return await self.call('SetCupRoundsPerChallenge', rounds)
  #

  async def get_cup_rounds_per_challenge(self) -> dict:
    """Get the number of rounds before going to next challenge in Cup mode. The struct returned contains two
    fields CurrentValue and NextValue."""
    return await self.call('GetCupRoundsPerChallenge')
  #

  async def set_cup_warm_up_duration(self, rounds: int) -> bool:
    """Set whether to enable the automatic warm-up phase in Cup mode. 0 = no, otherwise it's the duration of the
    phase, expressed in number of rounds. Only available to Admin. Requires a challenge restart to be taken
    into account."""
    return await self.call('SetCupWarmUpDuration', rounds)
  #

  async def get_cup_warm_up_duration(self) -> dict:
    """Get whether the automatic warm-up phase is enabled in Cup mode. The struct returned contains two fields
    CurrentValue and NextValue."""
    return await self.call('GetCupWarmUpDuration')
  #

  async def set_cup_nb_winners(self, count: int) -> bool:
    """Set the number of winners to determine before the match is considered over. Only available to Admin.
    Requires a challenge restart to be taken into account."""
    return await self.call('SetCupNbWinners', count)
  #

  async def get_cup_nb_winners(self) -> dict:
    """Get the number of winners to determine before the match is considered over. The struct returned contains
    two fields CurrentValue and NextValue."""
    return await self.call('GetCupNbWinners')
  #

  async def get_current_challenge_index(self) -> int:
    """Returns the current challenge index in the selection, or -1 if the challenge is no longer in the
    selection."""
    return await self.call('GetCurrentChallengeIndex')
  #

  async def get_next_challenge_index(self) -> int:
    """Returns the challenge index in the selection that will be played next (unless the current one is
    restarted...)"""
    return await self.call('GetNextChallengeIndex')
  #

  async def set_next_challenge_index(self, index: int) -> bool:
    """Sets the challenge index in the selection that will be played next (unless the current one is
    restarted...)"""
    return await self.call('SetNextChallengeIndex', index)
  #

  async def get_current_challenge_info(self) -> ChallengeInfo:
    """Returns a struct containing the infos for the current challenge. The struct contains the following fields
    : Name, UId, FileName, Author, Environnement, Mood, BronzeTime, SilverTime, GoldTime, AuthorTime,
    CopperPrice, LapRace, NbLaps and NbCheckpoints."""
    return await self.call('GetCurrentChallengeInfo')
  #

  async def get_next_challenge_info(self) -> ChallengeInfo:
    """Returns a struct containing the infos for the next challenge. The struct contains the following fields :
    Name, UId, FileName, Author, Environnement, Mood, BronzeTime, SilverTime, GoldTime, AuthorTime,
    CopperPrice and LapRace. (NbLaps and NbCheckpoints are also present but always set to -1)"""
    return await self.call('GetNextChallengeInfo')
  #

  async def get_challenge_info(self, filename: str) -> ChallengeInfo:
    """Returns a struct containing the infos for the challenge with the specified filename. The struct contains
    the following fields : Name, UId, FileName, Author, Environnement, Mood, BronzeTime, SilverTime, GoldTime,
    AuthorTime, CopperPrice and LapRace. (NbLaps and NbCheckpoints are also present but always set to -1)"""
    return await self.call('GetChallengeInfo', filename)
  #

  async def check_challenge_for_current_server_params(self, filename: str) -> bool:
    """Returns a boolean if the challenge with the specified filename matches the current server settings."""
    return await self.call('CheckChallengeForCurrentServerParams', filename)
  #

  async def get_challenge_list(self, count: int, start: int) -> list[ChallengeInfo]:
    """Returns a list of challenges among the current selection of the server. This method take two parameters.
    The first parameter specifies the maximum number of infos to be returned, and the second one the starting
    index in the selection. The list is an array of structures. Each structure contains the following fields :
    Name, UId, FileName, Environnement, Author, GoldTime and CopperPrice."""
    return await self.call('GetChallengeList', count, start)
  #

  async def add_challenge(self, filename: str) -> bool:
    """Add the challenge with the specified filename at the end of the current selection. Only available to
    Admin."""
    return await self.call('AddChallenge', filename)
  #

  async def add_challenge_list(self, filenames: list) -> int:
    """Add the list of challenges with the specified filenames at the end of the current selection. The list of
    challenges to add is an array of strings. Only available to Admin."""
    return await self.call('AddChallengeList', filenames)
  #

  async def remove_challenge(self, filename: str) -> bool:
    """Remove the challenge with the specified filename from the current selection. Only available to Admin."""
    return await self.call('RemoveChallenge', filename)
  #

  async def remove_challenge_list(self, filenames: list) -> int:
    """Remove the list of challenges with the specified filenames from the current selection. The list of
    challenges to remove is an array of strings. Only available to Admin."""
    return await self.call('RemoveChallengeList', filenames)
  #

  async def insert_challenge(self, filename: str) -> bool:
    """Insert the challenge with the specified filename after the current challenge. Only available to Admin."""
    return await self.call('InsertChallenge', filename)
  #

  async def insert_challenge_list(self, filenames: list) -> int:
    """Insert the list of challenges with the specified filenames after the current challenge. The list of
    challenges to insert is an array of strings. Only available to Admin."""
    return await self.call('InsertChallengeList', filenames)
  #

  async def choose_next_challenge(self, filename: str) -> bool:
    """Set as next challenge the one with the specified filename, if it is present in the selection. Only
    available to Admin."""
    return await self.call('ChooseNextChallenge', filename)
  #

  async def choose_next_challenge_list(self, filenames: list) -> int:
    """Set as next challenges the list of challenges with the specified filenames, if they are present in the
    selection. The list of challenges to choose is an array of strings. Only available to Admin."""
    return await self.call('ChooseNextChallengeList', filenames)
  #

  async def load_match_settings(self, filename: str) -> int:
    """Set a list of challenges defined in the playlist with the specified filename as the current selection of
    the server, and load the gameinfos from the same file. Only available to Admin."""
    return await self.call('LoadMatchSettings', filename)
  #

  async def append_playlist_from_match_settings(self, filename: str) -> int:
    """Add a list of challenges defined in the playlist with the specified filename at the end of the current
    selection. Only available to Admin."""
    return await self.call('AppendPlaylistFromMatchSettings', filename)
  #

  async def save_match_settings(self, filename: str) -> int:
    """Save the current selection of challenge in the playlist with the specified filename, as well as the
    current gameinfos. Only available to Admin."""
    return await self.call('SaveMatchSettings', filename)
  #

  async def insert_playlist_from_match_settings(self, filename: str) -> int:
    """Insert a list of challenges defined in the playlist with the specified filename after the current
    challenge. Only available to Admin."""
    return await self.call('InsertPlaylistFromMatchSettings', filename)
  #

  async def get_player_list(self, count: int, start: int, version: int = 1) -> list[PlayerInfo]:
    """Returns the list of players on the server. This method take two parameters. The first parameter specifies
    the maximum number of infos to be returned, and the second one the starting index in the list, an optional
    3rd parameter is used for compatibility: struct version (0 = united, 1 = forever, 2 = forever, including
    the servers). The list is an array of PlayerInfo structures. Forever PlayerInfo struct is: Login,
    NickName, PlayerId, TeamId, SpectatorStatus, LadderRanking, and Flags. LadderRanking is 0 when not in
    official mode, Flags = ForceSpectator(0,1,2) + IsReferee * 10 + IsPodiumReady * 100 + IsUsingStereoscopy *
    1000 + IsManagedByAnOtherServer * 10000 + IsServer * 100000 + HasPlayerSlot * 1000000 SpectatorStatus =
    Spectator + TemporarySpectator * 10 + PureSpectator * 100 + AutoTarget * 1000 + CurrentTargetId * 10000"""
    return await self.call('GetPlayerList', count, start, version)
  #

  async def get_player_info(self, login: str, version: int = 1) -> PlayerInfo:
    """Returns a struct containing the infos on the player with the specified login, with an optional parameter
    for compatibility: struct version (0 = united, 1 = forever). The structure is identical to the ones from
    GetPlayerList. Forever PlayerInfo struct is: Login, NickName, PlayerId, TeamId, SpectatorStatus,
    LadderRanking, and Flags. LadderRanking is 0 when not in official mode, Flags = ForceSpectator(0,1,2) +
    IsReferee * 10 + IsPodiumReady * 100 + IsUsingStereoscopy * 1000 + IsManagedByAnOtherServer * 10000 +
    IsServer * 100000 + HasPlayerSlot * 1000000 SpectatorStatus = Spectator + TemporarySpectator * 10 +
    PureSpectator * 100 + AutoTarget * 1000 + CurrentTargetId * 10000"""
    return await self.call('GetPlayerInfo', login, version)
  #

  async def get_detailed_player_info(self, login: str) -> dict:
    """Returns a struct containing the infos on the player with the specified login. The structure contains the
    following fields : Login, NickName, PlayerId, TeamId, IPAddress, DownloadRate, UploadRate, Language,
    IsSpectator, IsInOfficialMode, a structure named Avatar, an array of structures named Skins, a structure
    named LadderStats, HoursSinceZoneInscription and OnlineRights (0: nations account, 3: united account).
    Each structure of the array Skins contains two fields Environnement and a struct PackDesc. Each structure
    PackDesc, as well as the struct Avatar, contains two fields FileName and Checksum."""
    return await self.call('GetDetailedPlayerInfo', login)
  #

  async def get_main_server_player_info(self, version: int = 1) -> dict:
    """Returns a struct containing the player infos of the game server (ie: in case of a basic server, itself; in
    case of a relay server, the main server), with an optional parameter for compatibility: struct version (0
    = united, 1 = forever). The structure is identical to the ones from GetPlayerList. Forever PlayerInfo
    struct is: Login, NickName, PlayerId, TeamId, SpectatorStatus, LadderRanking, and Flags. LadderRanking is
    0 when not in official mode, Flags = ForceSpectator(0,1,2) + IsReferee * 10 + IsPodiumReady * 100 +
    IsUsingStereoscopy * 1000 + IsManagedByAnOtherServer * 10000 + IsServer * 100000 + HasPlayerSlot * 1000000
    SpectatorStatus = Spectator + TemporarySpectator * 10 + PureSpectator * 100 + AutoTarget * 1000 +
    CurrentTargetId * 10000"""
    return await self.call('GetMainServerPlayerInfo', version)
  #

  async def get_current_ranking(self, count: int, start: int) -> list[PlayerRanking]:
    """Returns the current rankings for the race in progress. (in team mode, the scores for the two teams are
    returned. In other modes, it's the individual players' scores) This method take two parameters. The first
    parameter specifies the maximum number of infos to be returned, and the second one the starting index in
    the ranking. The ranking returned is a list of structures. Each structure contains the following fields :
    Login, NickName, PlayerId, Rank, BestTime, Score, NbrLapsFinished and LadderScore. It also contains an
    array BestCheckpoints that contains the checkpoint times for the best race."""
    return await self.call('GetCurrentRanking', count, start)
  #

  async def get_current_ranking_for_login(self, login: str) -> list[PlayerRanking]:
    """Returns the current ranking for the race in progressof the player with the specified login (or list of
    comma-separated logins). The ranking returned is a list of structures, that contains the following fields
    : Login, NickName, PlayerId, Rank, BestTime, Score, NbrLapsFinished and LadderScore. It also contains an
    array BestCheckpoints that contains the checkpoint times for the best race."""
    return await self.call('GetCurrentRankingForLogin', login)
  #

  async def force_scores(self, scores: list, silent: bool) -> bool:
    """Force the scores of the current game. Only available in rounds and team mode. You have to pass an array of
    structs {int PlayerId, int Score}. And a boolean SilentMode - if true, the scores are silently updated
    (only available for SuperAdmin), allowing an external controller to do its custom counting... Only
    available to Admin/SuperAdmin."""
    return await self.call('ForceScores', scores, silent)
  #

  async def force_player_team(self, login: str, team: int) -> bool:
    """Force the team of the player. Only available in team mode. You have to pass the login and the team number
    (0 or 1). Only available to Admin."""
    return await self.call('ForcePlayerTeam', login, team)
  #

  async def force_player_team_id(self, player_id: int, team: int) -> bool:
    """Force the team of the player. Only available in team mode. You have to pass the playerid and the team
    number (0 or 1). Only available to Admin."""
    return await self.call('ForcePlayerTeamId', player_id, team)
  #

  async def force_spectator(self, login: str, mode: int) -> bool:
    """Force the spectating status of the player. You have to pass the login and the spectator mode (0: user
    selectable, 1: spectator, 2: player). Only available to Admin."""
    return await self.call('ForceSpectator', login, mode)
  #

  async def force_spectator_id(self, player_id: int, mode: int) -> bool:
    """Force the spectating status of the player. You have to pass the playerid and the spectator mode (0: user
    selectable, 1: spectator, 2: player). Only available to Admin."""
    return await self.call('ForceSpectatorId', player_id, mode)
  #

  async def force_spectator_target(self, spectator_login: str, target_login: str, camera: int) -> bool:
    """Force spectators to look at a specific player. You have to pass the login of the spectator (or '' for all)
    and the login of the target (or '' for automatic), and an integer for the camera type to use (-1 = leave
    unchanged, 0 = replay, 1 = follow, 2 = free). Only available to Admin."""
    return await self.call('ForceSpectatorTarget', spectator_login, target_login, camera)
  #

  async def force_spectator_target_id(self, spectator_id: int, target_id: int, camera: int) -> bool:
    """Force spectators to look at a specific player. You have to pass the id of the spectator (or -1 for all)
    and the id of the target (or -1 for automatic), and an integer for the camera type to use (-1 = leave
    unchanged, 0 = replay, 1 = follow, 2 = free). Only available to Admin."""
    return await self.call('ForceSpectatorTargetId', spectator_id, target_id, camera)
  #

  async def spectator_release_player_slot(self, login: str) -> bool:
    """Pass the login of the spectator. A spectator that once was a player keeps his player slot, so that he can
    go back to race mode. Calling this function frees this slot for another player to connect. Only available
    to Admin."""
    return await self.call('SpectatorReleasePlayerSlot', login)
  #

  async def spectator_release_player_slot_id(self, player_id: int) -> bool:
    """Pass the playerid of the spectator. A spectator that once was a player keeps his player slot, so that he
    can go back to race mode. Calling this function frees this slot for another player to connect. Only
    available to Admin."""
    return await self.call('SpectatorReleasePlayerSlotId', player_id)
  #

  async def manual_flow_control_enable(self, enable: bool) -> bool:
    """Enable control of the game flow: the game will wait for the caller to validate state transitions. Only
    available to Admin."""
    return await self.call('ManualFlowControlEnable', enable)
  #

  async def manual_flow_control_proceed(self) -> bool:
    """Allows the game to proceed. Only available to Admin."""
    return await self.call('ManualFlowControlProceed')
  #

  async def manual_flow_control_is_enabled(self) -> int:
    """Returns whether the manual control of the game flow is enabled. 0 = no, 1 = yes by the xml-rpc client
    making the call, 2 = yes, by some other xml-rpc client. Only available to Admin."""
    return await self.call('ManualFlowControlIsEnabled')
  #

  async def manual_flow_control_get_cur_transition(self) -> str:
    """Returns the transition that is currently blocked, or '' if none. (That's exactly the value last received
    by the callback.) Only available to Admin."""
    return await self.call('ManualFlowControlGetCurTransition')
  #

  async def check_end_match_condition(self) -> str:
    """Returns the current match ending condition. Return values are: 'Playing', 'ChangeMap' or 'Finished'."""
    return await self.call('CheckEndMatchCondition')
  #

  async def get_network_stats(self) -> dict:
    """Returns a struct containing the networks stats of the server. The structure contains the following fields
    : Uptime, NbrConnection, MeanConnectionTime, MeanNbrPlayer, RecvNetRate, SendNetRate, TotalReceivingSize,
    TotalSendingSize and an array of structures named PlayerNetInfos. Each structure of the array
    PlayerNetInfos contains the following fields : Login, IPAddress, LastTransferTime,
    DeltaBetweenTwoLastNetState, PacketLossRate. Only available to SuperAdmin."""
    return await self.call('GetNetworkStats')
  #

  async def start_server_lan(self) -> bool:
    """Start a server on lan, using the current configuration. Only available to SuperAdmin."""
    return await self.call('StartServerLan')
  #

  async def start_server_internet(self, account: dict) -> bool:
    """Start a server on internet using the 'Login' and 'Password' specified in the struct passed as parameters.
    Only available to SuperAdmin."""
    return await self.call('StartServerInternet', account)
  #

  async def get_status(self) -> Status:
    """Returns the current status of the server."""
    return await self.call('GetStatus')
  #

  async def quit_game(self) -> bool:
    """Quit the application. Only available to SuperAdmin."""
    return await self.call('QuitGame')
  #

  async def game_data_directory(self) -> str:
    """Returns the path of the game datas directory. Only available to Admin."""
    return await self.call('GameDataDirectory')
  #

  async def get_tracks_directory(self) -> str:
    """Returns the path of the tracks directory. Only available to Admin."""
    return await self.call('GetTracksDirectory')
  #

  async def get_skins_directory(self) -> str:
    """Returns the path of the skins directory. Only available to Admin."""
    return await self.call('GetSkinsDirectory')
  #
#
